When it comes to tax reporting, the most suitable data source is often the business document (for example, the invoice issued to the buyer/recipient). 

In some cases, however, required reporting data is not provided to a business recipient and is instead submitted only to the tax authority. 

To simplify reporting and standardize the required content, the PUF Tax Report specification has been developed. Currently this specification support reporting of Payments received.

=== How to get started with PUF

In the following chapters you can see which elements and what type of information that PUF supports. 

In some cases you will also get longer snippets of code and implementation guidelines in order how to properly provide the data. 

There is also a section with <<_examples>> that can be useful when implementing PUF. 

==== Working with XML schemas

* Download the PUF <<_xml_schemas>>.

NOTE: In the XML schemas provided in chapter <<_xml_schemas>> you will see the structure and the occurrences of every element available in PUF. +
This specification will not include any cardinality from a schema perspective nor from what is required in a specific legal domain since this might differ depending on which specific country, region or business requirements you will have to comply with. +
In order to know what information is sufficient to provide you should first check what the requirements from a legal and business perspective and then refer to this specification on where to provide this information.

=== Namespaces

*Target root name space - TaxReport:* 

- `urn:pagero:PageroUniversalFormat:TaxReport:1.0` +

*Example:* +
_TaxReport example for target namespace_
[source,xml]
----              
<TaxReport xmlns="urn:pagero:PageroUniversalFormat:TaxReport:1.0">
  <!-- Code omitted for clarity -->
</TaxReport >
----

=== Customization and Profile ID

To indicate the correct PUF specification identifer and the profile identifier, the values in below table must be sent in `cbc:CustomizationID` and `cbc:ProfileID`.

[%autowidth.stretch]
|===
|Type |Element `cbc:CustomizationID` |Element `cbc:ProfileID`

|*Tax report*
|urn:pagero.com:puf:taxreport:1.0
|urn:pagero.com:puf:taxreport:1.0
|===

*Example of CustomizationID and ProfileID:*
[source,xml]
----
<cbc:CustomizationID>urn:pagero.com:puf:taxreport:1.0</cbc:CustomizationID>
<cbc:ProfileID>urn:pagero.com:puf:taxreport:1.0</cbc:ProfileID>
----

// === Working with extensions

// This chapter provides an overview on how to use extensions.

// In order to facilitate the use of PUF specific extensions, a schema for the extensions is provided.

// The `PUF-ExtensionComponent.xsd` can be found together with the other schemas in chapter <<_xml_schemas>>. 

// To be able to use the `PUF-ExtensionComponent` a namespace must be included in the document file.

// *Example* +
// _Example from TaxReport_
// [source,xml]
// ----
// <TaxReport ... xmlns:puf="urn:pagero:ExtensionComponent:1.0">
//   <!-- Code omitted for clarity -->
// </TaxReport>
// ----

// Depending on in which context the `UBLExtensions` are used there are different options of what types of values you are able to provide.

// To identify which context the `UBLExtensions` is in the element ExtensionURI is used. 

// When using these Pagero extensions, the URI has the same base:

// - `urn:pagero:ExtensionComponent:1.0:PageroExtension`

// After the URI, the specific resource name is added.

// For detailed examples and how to use possible values in each extension please check the chapters where the PUF-specific elements are described.

=== Release management

PUF will be continuously updated to meet new market demands. 

==== Minor release

A minor release will always be backward compatible and will take place without prior notice and will be implemented whenever needed. 

Minor releases may include bugfixes, new elements, schematron updates and other features. 

These releases can be followed on https://github.com/pagero/puf[GitHub].

==== Major release

A major release may include changes that are not backward compatible. 

Such a release will be notified at least three months prior to date of implementation, to users who registered an account on Pagero validex or on https://github.com/pagero/puf[GitHub].

To register for PUF major release notification you can create a free account on https://pagero.validex.net[Pagero Validex]. 

But we urge all interested parties to follow the project on https://github.com/pagero/puf[GitHub] where all releases will be notified.
