Pagero Universal Format, hereafter referred to as "PUF", is a collection of business document specifications developed and maintained by https://www.pagero.com[Pagero Group^].

The XML-schema for PUF Tax Report is developed and maintained by Pagero but incorporates components from https://docs.oasis-open.org/ubl/UBL-2.3.html[Universal Business Language (UBL)]

https://pagero.github.io/puf[The PUF landing page^] lists all document types supported in the suite and in which directions these are available.

To align with new regulation and business needs throughout the world, the core idea of PUF is to enable its users to send/receive the data required to meet requirements in these markets and jurisdictions.

Based on extensive analysis, PUF has been designed to meet various country-, industry-, format- and/or system-specific requirements.

Another core idea of PUF is to create flexible, extendable business document specifications which can be updated quickly to meet the requirements of the fast-changing global electronic document landscape.

=== Version and changelog

.Version
|===
|Version |Date |Description
|1.0 |2026-02-05 |Beta version published
|===
